apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-app-container
        image:  muskansinghani228/retail-shopping:latest
        ports:
          - containerPort: 3001
        env:
         - name: MONGODB_URI
           value: "mongodb://retail:27017/Muskan"
      - name: retail
        image: mongo:latest
        ports:
           - containerPort: 27017